"""Backfill missing reasoning in assessment_responses.evaluation_metadata.

This script will:
- Find AssessmentResponse rows where evaluation_metadata.reasoning is missing or empty.
- If subscores or score exist in evaluation_metadata, synthesize a short explanation.
- Otherwise, use the service's fallback heuristic to generate a reasoning string.

Run with --dry-run to preview changes.
"""
import argparse
import logging
import json

from src.core.database import SessionLocal
from src.core.models import AssessmentResponse
from src.services.assessment_service import AssessmentService

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("backfill_assessment_response_reasoning")


def synthesize_from_metadata(meta: dict) -> str:
    if not isinstance(meta, dict):
        return "No reasoning available."
    parts = []
    score = meta.get("score") or meta.get("final_score") or meta.get("normalized_score")
    if score is not None:
        parts.append(f"Score: {int(score)}.")
    subs = meta.get("subscores")
    if isinstance(subs, dict) and subs:
        ss = ", ".join([f"{k}:{int(v)}" for k, v in subs.items()])
        parts.append(f"Subscores: {ss}.")
    rt = meta.get("rubric_type") or meta.get("type")
    if rt:
        parts.append(f"Rubric: {rt}.")
    if parts:
        return "Autogenerated: " + " ".join(parts)
    return "Autogenerated: No detailed metadata; heuristic applied." 


def backfill(dry_run: bool = True, limit: int = None, mode: str = "heuristic") -> int:
    svc = AssessmentService()
    db = SessionLocal()
    try:
        query = db.query(AssessmentResponse).filter(
            (AssessmentResponse.evaluation_metadata == None) |
            (AssessmentResponse.evaluation_metadata["reasoning"].astext == None) |
            (AssessmentResponse.evaluation_metadata["reasoning"].astext == "") |
            (AssessmentResponse.evaluation_metadata["reasoning"].astext == "No reasoning provided.")
        )
        if limit:
            query = query.limit(limit)
        rows = query.all()
        if not rows:
            logger.info("No responses require reasoning backfill.")
            return 0

        updated = 0
        samples = []
        for r in rows:
            meta = r.evaluation_metadata or {}
            reason = None
            new_meta = dict(meta)

            if mode == "llm":
                # Build a minimal question object similar to submit_answer
                qtext = r.question_text or ""
                question_obj = type("Question", (), {
                    "question_text": qtext,
                    "category": r.category or "general",
                    "driver": r.driver or "none",
                    "difficulty": r.difficulty or "medium",
                    "experience_band": None
                })()

                try:
                    eval_out = svc._run_coroutine_sync(svc._ensemble_evaluate(question_obj, r.raw_answer or ""))
                    if eval_out:
                        reason = eval_out.get("reasoning") or eval_out.get("rationale") or eval_out.get("explanation")
                        # attach subscores and raw_responses
                        if eval_out.get("subscores") is not None:
                            new_meta["subscores"] = eval_out.get("subscores")
                        if eval_out.get("raw_responses") is not None:
                            new_meta["raw_responses"] = eval_out.get("raw_responses")
                        new_meta["rubric_type"] = eval_out.get("rubric_type", "ensemble")
                        # update score if provided
                        if eval_out.get("score") is not None:
                            try:
                                r.score = int(eval_out.get("score"))
                            except Exception:
                                pass
                except Exception as e:
                    logger.exception(f"LLM re-eval failed for response {r.id}: {e}")

            if not reason:
                # Heuristic/metadata synthesis fallback
                reason = synthesize_from_metadata(meta)
                if reason.startswith("Autogenerated: No detailed"):
                    fb = svc._fallback_evaluation(r.raw_answer or "", r.driver or "none")
                    reason = fb.get("reasoning") or reason

            new_meta["reasoning"] = reason
            if mode != "llm":
                new_meta.setdefault("rubric_type", "fallback")

            samples.append({"id": str(r.id), "candidate": str(r.candidate_id), "reasoning": reason})

            if not dry_run:
                r.evaluation_metadata = new_meta
                db.add(r)
            updated += 1

        if not dry_run:
            db.commit()
            logger.info(f"Committed reasoning to {updated} responses.")
        else:
            logger.info(f"Dry-run: would update {updated} responses.")

        # log sample preview
        for s in samples[:5]:
            logger.info(f"Sample update: {s}")

        return updated
    finally:
        db.close()


def main():
    parser = argparse.ArgumentParser(description="Backfill assessment response reasoning")
    parser.add_argument("--dry-run", action="store_true", help="Do not commit changes")
    parser.add_argument("--limit", type=int, help="Limit number of rows to process")
    parser.add_argument("--mode", choices=["llm", "heuristic"], default="heuristic", help="Backfill mode: llm to re-evaluate using ensemble LLM, heuristic to synthesize from metadata")
    args = parser.parse_args()

    cnt = backfill(dry_run=args.dry_run, limit=args.limit, mode=args.mode)
    logger.info(f"Done. Rows processed: {cnt}")


if __name__ == "__main__":
    main()
